export const list: any[] = [
  {
    _id: '5f2959642a509b080a0a9ea4',
    projectCode: 'COD1',
    projectTitle: 'project1',
    projectInvestigator: 'Dr. Ariñez',
    projectStudent: 'jaime Contreras',
    projectDateStart: '01/02/2020',
    projectDateEnd: '01/02/2020',
    projectInstitution: 'Universidad Catolica Boliviana Cochabamba SP',
    projectFunding: '0',
    projectBudget: '0',
    projectProgress: '30',
    projectAbstract:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    userOwner: '5f0eaa11af6d10604f49f166',
    __v: 0,
    projectCurrency: 'Dollar Americano'
  },
  {
    _id: '5f295d2da69e390842663108',
    projectCode: 'G2P4',
    projectTitle: 'Codigo',
    projectInvestigator: 'Codigo',
    projectStudent: 'Codigo',
    projectDateStart: '2020-08-06T04:00:00.000Z',
    projectDateEnd: '2020-08-13T04:00:00.000Z',
    projectInstitution: 'Codigo',
    projectFunding: 'Codigo',
    projectBudget: '0',
    projectProgress: '50',
    projectAbstract: 'new proyecto',
    userOwner: '5f0eaa11af6d10604f49f166',
    __v: 0,
    projectCurrency: 'Peso Colombiano'
  },
  {
    _id: '5fc11dd7474890060341305b',
    projectCode: 'asdasd',
    projectTitle: 'asdasd',
    projectInvestigator: '',
    projectStudent: 'Carlos Arias',
    projectDateStart: '2020-10-26T04:00:00.000Z',
    projectDateEnd: '2020-11-29T04:00:00.000Z',
    projectInstitution: 'Universidad Mayor de San Simon',
    projectFunding: 'Centro de Investigacion de Ciencias Exactas e Ingenieria',
    projectBudget: '0',
    projectCurrency: 'Dollar Americano',
    projectProgress: '90',
    projectAbstract: 'asdadasd asda dasd asd asd asda dasd a',
    userOwner: '5f0eaa11af6d10604f49f166',
    __v: 0
  },
  {
    _id: '5fc11dd7474890060341305b',
    projectCode: 'asdasd',
    projectTitle: 'asdasd',
    projectInvestigator: '',
    projectStudent: 'Carlos Arias',
    projectDateStart: '2020-10-26T04:00:00.000Z',
    projectDateEnd: '2020-11-29T04:00:00.000Z',
    projectInstitution: 'Universidad Mayor de San Simon',
    projectFunding: 'Centro de Investigacion de Ciencias Exactas e Ingenieria',
    projectBudget: '0',
    projectCurrency: 'Dollar Americano',
    projectProgress: '90',
    projectAbstract: 'asdadasd asda dasd asd asd asda dasd a',
    userOwner: '5f0eaa11af6d10604f49f166',
    __v: 0
  }
];

export const dataLink: any[] = [
  {
    projects: [],
    publications: [],
    _id: '5f0eaa11af6d10604f49f166',
    user_name: 'Diego',
    user_lastname: 'Jaramillo',
    user_birthdate: '1980-01-01T04:00:00.000Z',
    user_mail: 'diego@gmail.com',
    user_degree: 'Magister',
    user_group: 'Ciencias de la Computación',
    user_line: 'L1 - Ingeniería de Software y Lenguajes de Programación',
    __v: 1
  },
  {
    projects: [],
    publications: [],
    _id: '5f24060cb03ff20c1897ae7c',
    user_name: 'Carlos',
    user_lastname: 'Arancibia',
    user_birthdate: '1980-01-09T04:00:00.000Z',
    user_mail: 'carancibia@gmail.com',
    user_degree: 'Licenciado',
    user_group: 'Estudios Ambientales',
    user_line: 'L3 - Contaminación Atmosférica',
    __v: 1
  },
  {
    projects: [],
    publications: [],
    _id: '5f3b5e9ca6ac1d66616b954a',
    user_name: 'Marvin',
    user_birthdate: '0312-01-01T04:32:36.000Z',
    user_mail: 'mramirez@gmail.com',
    user_degree: 'Magister',
    user_group: 'Ciencias de la Computación',
    user_line: 'L1 - Ingeniería de Software y Lenguajes de Programación',
    __v: 0,
    user_lastname: 'Ramirez'
  },
  {
    projects: [],
    publications: [],
    _id: '5fa30af73d2cd40017a7b94b',
    user_name: 'Juan',
    user_lastname: 'Perez',
    user_birthdate: '2002-01-01T04:00:00.000Z',
    user_mail: 'fesadfsd@gmail.com',
    user_degree: 'Licenciado',
    user_group: 'Ciencias del Hábitat y la Construcción',
    user_line: 'L1 - Gestión de la construcción',
    __v: 0
  },
  {
    projects: [],
    publications: [],
    _id: '6012b93b5e1c080680765e23',
    user_name: 'Bryan ',
    user_lastname: 'Villarroel',
    user_birthdate: '1980-04-17T04:00:00.000Z',
    user_mail: 'bvillarroel@cicei.com',
    user_degree: 'Licenciado',
    user_group: 'Ciencias del Hábitat y la Construcción',
    user_line: 'L2 - Infraestructura Urbana',
    user_resume: 'Bryan Villarroel Licenciado en ....... pertenece al CICEI',
    __v: 0
  }
];
